import { Business, Event, Housing, Job } from './types';

export const BUSINESSES: Business[] = [
  {
    id: 'b1',
    type: 'business',
    name: 'Al-Sham Halal Restaurant',
    category: 'halal',
    description: 'Authentic Middle Eastern halal cuisine featuring shawarma, falafel, and grilled meats in a warm family atmosphere.',
    address: '1234 Market Street',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19103',
    phone: '(215) 555-0101',
    website: 'https://example.com',
    rating: 4.8,
    reviewCount: 342,
    isOpen: true,
    hours: 'Mon-Sun 10am-10pm',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
    tags: ['halal', 'middle eastern', 'shawarma', 'family friendly'],
    priceLevel: 2,
  },
  {
    id: 'b2',
    type: 'business',
    name: 'Karachi Kitchen',
    category: 'restaurant',
    description: 'Traditional Pakistani cuisine with biryanis, karahi, and fresh naan bread baked daily.',
    address: '567 Oak Avenue',
    city: 'Chicago',
    state: 'IL',
    zip: '60601',
    phone: '(312) 555-0102',
    rating: 4.6,
    reviewCount: 218,
    isOpen: true,
    hours: 'Mon-Sun 11am-11pm',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80',
    tags: ['halal', 'pakistani', 'biryani', 'curry'],
    priceLevel: 2,
  },
  {
    id: 'b3',
    type: 'business',
    name: 'Masjid Al-Noor',
    category: 'mosque',
    description: 'Community mosque serving the Muslim community with daily prayers, Jummah services, and educational programs.',
    address: '890 Elm Street',
    city: 'New York',
    state: 'NY',
    zip: '10001',
    phone: '(212) 555-0103',
    rating: 4.9,
    reviewCount: 567,
    isOpen: true,
    hours: 'Open 24/7 for prayers',
    image: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800&q=80',
    tags: ['mosque', 'islamic center', 'prayers', 'community'],
    priceLevel: 1,
  },
  {
    id: 'b4',
    type: 'business',
    name: 'Green Valley Grocers',
    category: 'grocery',
    description: 'Full-service halal grocery store with fresh produce, imported spices, and a wide selection of halal meats.',
    address: '321 Pine Road',
    city: 'Houston',
    state: 'TX',
    zip: '77001',
    phone: '(713) 555-0104',
    rating: 4.5,
    reviewCount: 189,
    isOpen: true,
    hours: 'Mon-Sat 8am-9pm, Sun 9am-7pm',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80',
    tags: ['halal', 'grocery', 'fresh produce', 'spices'],
    priceLevel: 2,
  },
  {
    id: 'b5',
    type: 'business',
    name: 'Mediterranean Grill House',
    category: 'halal',
    description: 'Upscale Mediterranean dining with halal certified meats, fresh seafood, and traditional mezze.',
    address: '456 Cedar Blvd',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90001',
    phone: '(213) 555-0105',
    rating: 4.7,
    reviewCount: 423,
    isOpen: false,
    hours: 'Tue-Sun 12pm-10pm',
    image: 'https://images.unsplash.com/photo-1544148103-0773bf10d330?w=800&q=80',
    tags: ['halal', 'mediterranean', 'seafood', 'upscale'],
    priceLevel: 3,
  },
  {
    id: 'b6',
    type: 'business',
    name: 'Nile Valley Restaurant',
    category: 'halal',
    description: 'Egyptian and North African specialties including koshari, ful medames, and freshly grilled meats.',
    address: '789 Maple Street',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19104',
    phone: '(215) 555-0106',
    rating: 4.4,
    reviewCount: 156,
    isOpen: true,
    hours: 'Mon-Sun 11am-9pm',
    image: 'https://images.unsplash.com/photo-1540914124281-342587941389?w=800&q=80',
    tags: ['halal', 'egyptian', 'north african', 'casual'],
    priceLevel: 2,
  },
  {
    id: 'b7',
    type: 'business',
    name: 'Islamic Learning Center',
    category: 'school',
    description: 'Full-time Islamic school offering K-12 education with Quran studies, Arabic language, and STEM curriculum.',
    address: '1100 University Drive',
    city: 'Dallas',
    state: 'TX',
    zip: '75201',
    phone: '(214) 555-0107',
    rating: 4.8,
    reviewCount: 234,
    isOpen: true,
    hours: 'Mon-Fri 7:30am-4pm',
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80',
    tags: ['school', 'islamic', 'education', 'k-12'],
    priceLevel: 2,
  },
  {
    id: 'b8',
    type: 'business',
    name: 'Amanat Health Clinic',
    category: 'healthcare',
    description: 'Muslim-owned medical clinic offering primary care, preventive medicine, and specialty referrals.',
    address: '2200 Health Blvd',
    city: 'Chicago',
    state: 'IL',
    zip: '60602',
    phone: '(312) 555-0108',
    rating: 4.6,
    reviewCount: 312,
    isOpen: true,
    hours: 'Mon-Fri 8am-6pm, Sat 9am-2pm',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80',
    tags: ['healthcare', 'clinic', 'primary care', 'muslim-owned'],
    priceLevel: 2,
  },
  {
    id: 'b9',
    type: 'business',
    name: 'Zaytoun Bakery',
    category: 'restaurant',
    description: 'Artisan halal bakery specializing in Middle Eastern pastries, breads, and custom cakes.',
    address: '555 Baker Street',
    city: 'New York',
    state: 'NY',
    zip: '10002',
    phone: '(212) 555-0109',
    rating: 4.9,
    reviewCount: 445,
    isOpen: true,
    hours: 'Mon-Sat 7am-8pm',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80',
    tags: ['halal', 'bakery', 'pastries', 'custom cakes'],
    priceLevel: 2,
  },
  {
    id: 'b10',
    type: 'business',
    name: 'Saffron Palace',
    category: 'halal',
    description: 'Elegant Persian restaurant serving traditional Iranian dishes including ghormeh sabzi and kebabs.',
    address: '888 Persian Way',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90002',
    phone: '(213) 555-0110',
    rating: 4.5,
    reviewCount: 278,
    isOpen: true,
    hours: 'Tue-Sun 5pm-11pm',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    tags: ['halal', 'persian', 'iranian', 'fine dining'],
    priceLevel: 3,
  },
  {
    id: 'b11',
    type: 'business',
    name: 'Spice Route Indian Cuisine',
    category: 'halal',
    description: 'Award-winning halal Indian restaurant with authentic curries, tandoor dishes, and vegetarian options.',
    address: '1456 Curry Lane',
    city: 'New York',
    state: 'NY',
    zip: '10003',
    phone: '(212) 555-0111',
    rating: 4.7,
    reviewCount: 389,
    isOpen: true,
    hours: 'Mon-Sun 12pm-10:30pm',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80',
    tags: ['halal', 'indian', 'curry', 'tandoor'],
    priceLevel: 2,
  },
  {
    id: 'b12',
    type: 'business',
    name: 'Al-Furqan Islamic Center',
    category: 'mosque',
    description: 'Large Islamic center with mosque, school, social services, and community hall.',
    address: '3000 Community Blvd',
    city: 'Houston',
    state: 'TX',
    zip: '77002',
    phone: '(713) 555-0112',
    rating: 4.8,
    reviewCount: 678,
    isOpen: true,
    hours: 'Daily prayers, office Mon-Fri 9am-5pm',
    image: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=800&q=80',
    tags: ['mosque', 'islamic center', 'community', 'school'],
    priceLevel: 1,
  },
  {
    id: 'b13',
    type: 'business',
    name: 'Baraka Halal Butcher',
    category: 'grocery',
    description: 'Premium halal butcher shop with fresh-cut meats, specialty cuts, and marinated products.',
    address: '677 Meat Market Way',
    city: 'Dallas',
    state: 'TX',
    zip: '75202',
    phone: '(214) 555-0113',
    rating: 4.6,
    reviewCount: 201,
    isOpen: true,
    hours: 'Tue-Sun 9am-7pm',
    image: 'https://images.unsplash.com/photo-1588347785102-2944a9259168?w=800&q=80',
    tags: ['halal', 'butcher', 'meat', 'fresh'],
    priceLevel: 2,
  },
  {
    id: 'b14',
    type: 'business',
    name: 'Andalus Cafe',
    category: 'restaurant',
    description: 'Cozy Moroccan-inspired cafe serving mint tea, pastillas, tagines, and artisan coffee.',
    address: '234 Medina Street',
    city: 'Chicago',
    state: 'IL',
    zip: '60603',
    phone: '(312) 555-0114',
    rating: 4.5,
    reviewCount: 167,
    isOpen: true,
    hours: 'Mon-Sun 8am-10pm',
    image: 'https://images.unsplash.com/photo-1493770348161-369560ae357d?w=800&q=80',
    tags: ['halal', 'moroccan', 'cafe', 'tea'],
    priceLevel: 2,
  },
  {
    id: 'b15',
    type: 'business',
    name: 'Crescent Moon Sweets',
    category: 'restaurant',
    description: 'Halal dessert shop featuring baklava, kunafa, ice cream, and fresh-made sweets.',
    address: '910 Sweet Street',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19105',
    phone: '(215) 555-0115',
    rating: 4.8,
    reviewCount: 334,
    isOpen: true,
    hours: 'Mon-Sun 10am-11pm',
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=800&q=80',
    tags: ['halal', 'desserts', 'baklava', 'sweets'],
    priceLevel: 1,
  },
];

export const EVENTS: Event[] = [
  {
    id: 'e1',
    type: 'event',
    title: 'Annual Muslim Community Fundraiser Gala',
    description: 'Join us for an elegant evening supporting local community initiatives. Includes dinner, keynote speakers, and live entertainment.',
    category: 'fundraiser',
    date: '2026-06-15',
    time: '6:00 PM',
    endTime: '10:00 PM',
    location: 'Philadelphia Convention Center',
    city: 'Philadelphia',
    state: 'PA',
    organizer: 'Philadelphia Muslim Community Council',
    attendees: 245,
    maxAttendees: 500,
    price: 75,
    isFree: false,
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&q=80',
    tags: ['fundraiser', 'gala', 'community', 'dinner'],
  },
  {
    id: 'e2',
    type: 'event',
    title: 'Eid Al-Adha Community Celebration',
    description: 'Community Eid celebration with prayers, food, children activities, and cultural performances.',
    category: 'religious',
    date: '2026-06-07',
    time: '8:00 AM',
    endTime: '2:00 PM',
    location: 'Riverside Park',
    city: 'New York',
    state: 'NY',
    organizer: 'NYC Muslim Alliance',
    attendees: 1200,
    price: 0,
    isFree: true,
    image: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800&q=80',
    tags: ['eid', 'celebration', 'family', 'free'],
  },
  {
    id: 'e3',
    type: 'event',
    title: 'Halal Food Festival 2026',
    description: 'Three days of amazing halal food vendors, cooking demonstrations, and cultural entertainment from around the world.',
    category: 'food',
    date: '2026-07-04',
    time: '11:00 AM',
    endTime: '9:00 PM',
    location: 'Grant Park',
    city: 'Chicago',
    state: 'IL',
    organizer: 'Chicago Food Festival Organization',
    attendees: 3400,
    maxAttendees: 10000,
    price: 15,
    isFree: false,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    tags: ['food festival', 'halal', 'cultural', 'family'],
  },
  {
    id: 'e4',
    type: 'event',
    title: 'Islamic Finance Workshop',
    description: 'Learn about halal investing, Islamic mortgages, and riba-free financial planning from certified experts.',
    category: 'education',
    date: '2026-06-20',
    time: '10:00 AM',
    endTime: '4:00 PM',
    location: 'Dallas Convention Center',
    city: 'Dallas',
    state: 'TX',
    organizer: 'Islamic Finance Institute',
    attendees: 87,
    maxAttendees: 150,
    price: 45,
    isFree: false,
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80',
    tags: ['finance', 'islamic', 'workshop', 'education'],
  },
  {
    id: 'e5',
    type: 'event',
    title: 'Sisters Circle Monthly Meeting',
    description: 'Monthly gathering for Muslim women featuring guest speakers, networking, and community support.',
    category: 'community',
    date: '2026-06-08',
    time: '2:00 PM',
    endTime: '5:00 PM',
    location: 'Al-Noor Islamic Center',
    city: 'Houston',
    state: 'TX',
    organizer: 'Sisters Circle Organization',
    attendees: 45,
    maxAttendees: 80,
    price: 0,
    isFree: true,
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&q=80',
    tags: ['women', 'community', 'networking', 'free'],
  },
  {
    id: 'e6',
    type: 'event',
    title: 'Youth Basketball Tournament',
    description: 'Annual Muslim youth basketball tournament open to ages 12-18. Registration includes jersey and lunch.',
    category: 'sports',
    date: '2026-06-14',
    time: '9:00 AM',
    endTime: '6:00 PM',
    location: 'Community Sports Complex',
    city: 'Los Angeles',
    state: 'CA',
    organizer: 'Muslim Youth Sports League',
    attendees: 120,
    maxAttendees: 200,
    price: 25,
    isFree: false,
    image: 'https://images.unsplash.com/photo-1546519638405-a9f87a3fcbe2?w=800&q=80',
    tags: ['sports', 'youth', 'basketball', 'tournament'],
  },
  {
    id: 'e7',
    type: 'event',
    title: 'Quran Memorization Competition',
    description: 'Annual Quran recitation and memorization competition for youth and adults. Multiple categories and prizes.',
    category: 'religious',
    date: '2026-06-28',
    time: '10:00 AM',
    endTime: '5:00 PM',
    location: 'Philadelphia Convention Center',
    city: 'Philadelphia',
    state: 'PA',
    organizer: 'Islamic Educational Foundation',
    attendees: 340,
    price: 0,
    isFree: true,
    image: 'https://images.unsplash.com/photo-1519817914152-22d216bb9170?w=800&q=80',
    tags: ['quran', 'competition', 'youth', 'education'],
  },
  {
    id: 'e8',
    type: 'event',
    title: 'Tech for Good: Muslim Entrepreneurs Summit',
    description: 'Connect with Muslim tech entrepreneurs, investors, and innovators. Keynotes, workshops, and networking.',
    category: 'business',
    date: '2026-07-10',
    time: '8:00 AM',
    endTime: '6:00 PM',
    location: 'WeWork Downtown',
    city: 'New York',
    state: 'NY',
    organizer: 'Muslim Entrepreneurs Network',
    attendees: 280,
    maxAttendees: 400,
    price: 99,
    isFree: false,
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
    tags: ['tech', 'entrepreneurship', 'networking', 'business'],
  },
];

export const HOUSING: Housing[] = [
  {
    id: 'h1',
    type: 'housing',
    title: 'Modern 2BR Apartment in Center City',
    description: 'Bright and spacious 2-bedroom apartment in the heart of Philadelphia. Newly renovated with modern finishes, open kitchen, and city views.',
    address: '1500 JFK Blvd, Unit 8C',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19102',
    price: 1850,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 950,
    propertyType: 'apartment',
    listingType: 'rent',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80',
    ],
    amenities: ['gym', 'rooftop', 'doorman', 'dishwasher', 'laundry in building'],
    contactName: 'Sarah Johnson',
    contactPhone: '(215) 555-2001',
    contactEmail: 'sarah@realtyco.com',
    postedDate: '2026-05-15',
    available: true,
    petFriendly: false,
    parking: false,
  },
  {
    id: 'h2',
    type: 'housing',
    title: 'Spacious Studio in Wicker Park',
    description: 'Cozy studio apartment in the vibrant Wicker Park neighborhood. Close to shops, restaurants, and public transit.',
    address: '2100 N Milwaukee Ave, Unit 3',
    city: 'Chicago',
    state: 'IL',
    zip: '60647',
    price: 1100,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 550,
    propertyType: 'studio',
    listingType: 'rent',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    ],
    amenities: ['hardwood floors', 'high ceilings', 'in-unit laundry'],
    contactName: 'Mike Chen',
    contactPhone: '(312) 555-2002',
    contactEmail: 'mchen@homefinders.com',
    postedDate: '2026-05-18',
    available: true,
    petFriendly: true,
    parking: false,
  },
  {
    id: 'h3',
    type: 'housing',
    title: 'Beautiful 3BR Family Home for Sale',
    description: 'Stunning single-family home in a quiet Houston neighborhood. Updated kitchen, large backyard, and excellent school district.',
    address: '4521 Maple Grove Lane',
    city: 'Houston',
    state: 'TX',
    zip: '77056',
    price: 385000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1850,
    propertyType: 'house',
    listingType: 'sale',
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    ],
    amenities: ['garage', 'backyard', 'central AC', 'updated kitchen', 'storage'],
    contactName: 'David Williams',
    contactPhone: '(713) 555-2003',
    contactEmail: 'dwilliams@homerealty.com',
    postedDate: '2026-05-10',
    available: true,
    petFriendly: true,
    parking: true,
  },
  {
    id: 'h4',
    type: 'housing',
    title: 'Luxury 1BR Condo with Manhattan Views',
    description: 'High-end condo with breathtaking Manhattan skyline views, premium finishes, and world-class amenities.',
    address: '200 Hudson Street, Unit 45F',
    city: 'New York',
    state: 'NY',
    zip: '10013',
    price: 3200,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 750,
    propertyType: 'condo',
    listingType: 'rent',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    ],
    amenities: ['concierge', 'pool', 'gym', 'rooftop terrace', 'valet parking'],
    contactName: 'Jennifer Park',
    contactPhone: '(212) 555-2004',
    contactEmail: 'jpark@luxurynyc.com',
    postedDate: '2026-05-20',
    available: true,
    petFriendly: false,
    parking: true,
  },
  {
    id: 'h5',
    type: 'housing',
    title: 'Affordable 2BR Apartment Near Masjid',
    description: 'Comfortable apartment walking distance to the local masjid and halal grocery stores. Great Muslim community area.',
    address: '789 Community Drive, Apt 2B',
    city: 'Chicago',
    state: 'IL',
    zip: '60629',
    price: 1050,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 900,
    propertyType: 'apartment',
    listingType: 'rent',
    images: [
      'https://images.unsplash.com/photo-1565182999561-18d7dc61c393?w=800&q=80',
    ],
    amenities: ['laundry in building', 'storage', 'close to transit'],
    contactName: 'Ahmed Hassan',
    contactPhone: '(312) 555-2005',
    contactEmail: 'ahmed@communityhousing.com',
    postedDate: '2026-05-12',
    available: true,
    petFriendly: false,
    parking: true,
  },
  {
    id: 'h6',
    type: 'housing',
    title: '4BR Townhouse in Dallas Suburbs',
    description: 'Spacious townhouse perfect for a growing family. New construction with modern amenities and excellent schools nearby.',
    address: '3300 Suburban Way',
    city: 'Dallas',
    state: 'TX',
    zip: '75240',
    price: 2400,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2100,
    propertyType: 'townhouse',
    listingType: 'rent',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    ],
    amenities: ['garage', 'backyard', 'community pool', 'gym', 'playground'],
    contactName: 'Rachel Torres',
    contactPhone: '(214) 555-2006',
    contactEmail: 'rtorres@dallasprops.com',
    postedDate: '2026-05-08',
    available: true,
    petFriendly: true,
    parking: true,
  },
];

export const JOBS: Job[] = [
  {
    id: 'j1',
    type: 'job',
    title: 'Software Engineer - Full Stack',
    company: 'TechVision Inc.',
    description: 'Join our growing team building the next generation of community platforms. We use React, Node.js, and AWS.',
    category: 'technology',
    city: 'New York',
    state: 'NY',
    salary: '$95,000 - $130,000/year',
    salaryMin: 95000,
    salaryMax: 130000,
    jobType: 'full-time',
    remote: true,
    experience: '3-5 years',
    requirements: ['React', 'Node.js', 'TypeScript', 'AWS', 'PostgreSQL'],
    benefits: ['health insurance', '401k', 'flexible hours', 'remote work', 'stock options'],
    contactEmail: 'careers@techvision.com',
    postedDate: '2026-05-18',
    deadline: '2026-06-30',
  },
  {
    id: 'j2',
    type: 'job',
    title: 'Delivery Driver - Part Time',
    company: 'QuickDeliver',
    description: 'Flexible delivery driver position. Set your own hours, work when you want. Halal-friendly workplace.',
    category: 'delivery',
    city: 'Chicago',
    state: 'IL',
    salary: '$18 - $25/hour',
    salaryMin: 18,
    salaryMax: 25,
    jobType: 'part-time',
    remote: false,
    experience: 'No experience required',
    requirements: ['valid drivers license', 'clean driving record', 'smartphone'],
    benefits: ['flexible schedule', 'weekly pay', 'gas reimbursement'],
    contactEmail: 'drivers@quickdeliver.com',
    postedDate: '2026-05-20',
  },
  {
    id: 'j3',
    type: 'job',
    title: 'Halal Restaurant Manager',
    company: 'Al-Sham Restaurant Group',
    description: 'Experienced restaurant manager needed for our growing chain of halal restaurants in Philadelphia.',
    category: 'food service',
    city: 'Philadelphia',
    state: 'PA',
    salary: '$55,000 - $70,000/year',
    salaryMin: 55000,
    salaryMax: 70000,
    jobType: 'full-time',
    remote: false,
    experience: '3+ years restaurant management',
    requirements: ['restaurant management experience', 'food safety certification', 'leadership skills', 'bilingual preferred'],
    benefits: ['health insurance', 'employee meals', 'paid vacation', 'performance bonus'],
    contactEmail: 'hr@alshamgroup.com',
    postedDate: '2026-05-15',
    deadline: '2026-06-15',
  },
  {
    id: 'j4',
    type: 'job',
    title: 'Islamic Studies Teacher',
    company: 'Al-Furqan Academy',
    description: 'Full-time Islamic Studies teacher for grades 6-12. Must have knowledge of Quran, Hadith, and Islamic history.',
    category: 'education',
    city: 'Houston',
    state: 'TX',
    salary: '$45,000 - $58,000/year',
    salaryMin: 45000,
    salaryMax: 58000,
    jobType: 'full-time',
    remote: false,
    experience: '2+ years teaching',
    requirements: ['teaching certification', 'Islamic knowledge', 'Arabic preferred', 'bachelor degree'],
    benefits: ['health insurance', 'summer break', 'tuition discount for children', 'retirement plan'],
    contactEmail: 'principal@alfurqanacademy.com',
    postedDate: '2026-05-10',
    deadline: '2026-07-01',
  },
  {
    id: 'j5',
    type: 'job',
    title: 'Marketing Manager - Remote',
    company: 'HalalBrands Digital',
    description: 'Lead digital marketing campaigns for halal brands across the US. Strategy, content, and analytics.',
    category: 'marketing',
    city: 'Dallas',
    state: 'TX',
    salary: '$70,000 - $90,000/year',
    salaryMin: 70000,
    salaryMax: 90000,
    jobType: 'full-time',
    remote: true,
    experience: '4+ years marketing',
    requirements: ['digital marketing', 'SEO/SEM', 'social media', 'analytics', 'content strategy'],
    benefits: ['remote work', 'health insurance', '401k', 'professional development budget'],
    contactEmail: 'jobs@halalbrands.com',
    postedDate: '2026-05-17',
  },
  {
    id: 'j6',
    type: 'job',
    title: 'Medical Assistant',
    company: 'Crescent Health Center',
    description: 'Medical assistant position at busy Muslim-owned health clinic. Clinical and administrative duties.',
    category: 'healthcare',
    city: 'Chicago',
    state: 'IL',
    salary: '$17 - $22/hour',
    salaryMin: 17,
    salaryMax: 22,
    jobType: 'full-time',
    remote: false,
    experience: '1-2 years',
    requirements: ['MA certification', 'EHR experience', 'bilingual (Arabic/Urdu preferred)', 'CPR certified'],
    benefits: ['health insurance', 'dental', 'vision', 'paid time off', 'training'],
    contactEmail: 'hr@crescenthealth.com',
    postedDate: '2026-05-19',
  },
  {
    id: 'j7',
    type: 'job',
    title: 'Warehouse Associate',
    company: 'HalalMart Distribution',
    description: 'Full-time warehouse position at halal food distribution center. Day shifts available. Prayer accommodations provided.',
    category: 'warehouse',
    city: 'New York',
    state: 'NY',
    salary: '$19 - $23/hour',
    salaryMin: 19,
    salaryMax: 23,
    jobType: 'full-time',
    remote: false,
    experience: 'Entry level',
    requirements: ['ability to lift 50 lbs', 'forklift license preferred', 'reliable transportation'],
    benefits: ['health insurance', 'overtime pay', 'prayer room', 'halal meals'],
    contactEmail: 'jobs@halalmart.com',
    postedDate: '2026-05-21',
  },
  {
    id: 'j8',
    type: 'job',
    title: 'UX Designer - Contract',
    company: 'Freelance via MuslimTech',
    description: '6-month contract UX design role for an Islamic fintech startup. Remote-friendly, flexible hours.',
    category: 'design',
    city: 'Los Angeles',
    state: 'CA',
    salary: '$60 - $85/hour',
    salaryMin: 60,
    salaryMax: 85,
    jobType: 'contract',
    remote: true,
    experience: '3+ years UX design',
    requirements: ['Figma', 'user research', 'prototyping', 'design systems', 'fintech experience preferred'],
    benefits: ['remote work', 'flexible hours', 'portfolio projects'],
    contactEmail: 'contracts@muslimtech.io',
    postedDate: '2026-05-16',
  },
];

export const US_CITIES = [
  { city: 'New York', state: 'NY' },
  { city: 'Los Angeles', state: 'CA' },
  { city: 'Chicago', state: 'IL' },
  { city: 'Houston', state: 'TX' },
  { city: 'Philadelphia', state: 'PA' },
  { city: 'Dallas', state: 'TX' },
  { city: 'Atlanta', state: 'GA' },
  { city: 'Seattle', state: 'WA' },
  { city: 'Boston', state: 'MA' },
  { city: 'Miami', state: 'FL' },
  { city: 'Phoenix', state: 'AZ' },
  { city: 'Denver', state: 'CO' },
  { city: 'Minneapolis', state: 'MN' },
  { city: 'Detroit', state: 'MI' },
  { city: 'Kansas City', state: 'MO' },
  { city: 'San Francisco', state: 'CA' },
  { city: 'Austin', state: 'TX' },
  { city: 'Charlotte', state: 'NC' },
  { city: 'Columbus', state: 'OH' },
  { city: 'Indianapolis', state: 'IN' },
  { city: 'Nashville', state: 'TN' },
  { city: 'Baltimore', state: 'MD' },
  { city: 'Louisville', state: 'KY' },
  { city: 'Portland', state: 'OR' },
  { city: 'Las Vegas', state: 'NV' },
  { city: 'San Diego', state: 'CA' },
  { city: 'Tampa', state: 'FL' },
  { city: 'Sacramento', state: 'CA' },
  { city: 'Pittsburgh', state: 'PA' },
  { city: 'Cincinnati', state: 'OH' },
];

export const ALL_LISTINGS = [...BUSINESSES, ...EVENTS, ...HOUSING, ...JOBS];
